Date::DATE_FORMATS[:mdy]       = '%m-%d-%Y'
Time::DATE_FORMATS[:mdy]       = '%m-%d-%Y'
Time::DATE_FORMATS[:just_time] = '%I:%M %p'
Time::DATE_FORMATS[:file_name] = '%b-%-d-%Y'
Time::DATE_FORMATS[:human]     = '%B %-d, %Y %l:%M %p'
